#!/usr/bin/env python3
"""
tests/test_sprite_geometry.py — the bench/window split geometry gate
(Phase 26.5, Plan 06, SC-3 — Wave-0 item 2).

The window seat baked into rows 54-61 of the 44x62 decor-window canvas
becomes its own object: the three time-of-day windows re-cut to 44x44
(88x88 after the 2x upscale) and the terracotta-cushion bench born as
bench.png (44x8 -> 88x16) — deterministic codegen, verifiable without a
browser. Three geometry registries (index.html, app.js, server.py) must
agree or a legitimate design-mode drag is silently refused (Pitfall 7);
app.js SCENE.surfaces entries [0]/[1] are hard-coded consumers' ground
(the spine renderer, the candle home — Pitfall 3), so the bench joins
APPEND-ONLY at index [2].

Stdlib only (unittest + subprocess + struct) — the zero-dependency law.
Sources are read as text for the registry pins (the test_diegetic_wiring
house style, in python); the layout acceptance is functional (server.py
imports clean with no socket bound — the test_server_smoke proof).

Coverage (26.5-06 Tasks 1-2):

  1. DETERMINISTIC REGENERATION — `python3 tools/gen_room_sprites.py`
     runs clean (exit 0) before any assertion, so every dimension pin
     below holds against freshly regenerated bytes, not stale disk.
  2. PNG DIMENSIONS — decor-window.png / decor-window-dusk.png /
     decor-window-night.png parse as 88x88 and bench.png parses as
     88x16, straight from the IHDR bytes (struct.unpack of bytes 16-24).
  3. REGISTRY AGREEMENT (Pitfall 7) — the same geometry in all three
     registries: index.html's window button carries --h:88 and a
     #room-obj-bench button pinned at --x:124;--y:152;--w:88;--h:16;
     app.js carries the window 88x88 in BOTH CATALOG and CAT_SPRITES
     plus bench entries in both and 'bench' in ROOM_OBJECT_IDS;
     server.py LAYOUT_OBJECTS carries the window (88, 88, "wall") row
     plus the bench (88, 16, "floorwall") row — and validate_layout accepts
     an in-bounds, on-grid bench position post (functional, not grep).
  4. SCENE PINS (Pitfall 3) — app.js SCENE.surfaces holds the shipped
     entry strings for indices [0] and [1] byte-identical, FOLLOWED by
     the appended bench entry { x0: 124, x1: 212, y: 152 } (the cushion
     top IS the drawn wood — the desk-line lesson).

  5. THE STICKER SHEET REGENERATION GATE (26.9-04) — four steps, in order,
     over assets/room/notebook-stickers.png. See the block comment above
     TestStickerSheetRegenGate for why steps 1 and 4 exist and why NEITHER
     may ever be removed as redundant.
"""
import hashlib
import json
import re
import struct
import subprocess
import sys
import unittest
from pathlib import Path
import zlib

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import server  # noqa: E402  — importable with no socket bound (smoke proof)

ROOM = REPO_ROOT / "assets" / "room"
GENERATOR = REPO_ROOT / "tools" / "gen_room_sprites.py"

# The four split sprites and their pinned full-res dimensions (SC-3),
# plus the chair (26.5-09 UAT F16: promoted to an arrangeable object, so
# its geometry joins the three-registry agreement gate below).
PINNED_DIMS = {
    "decor-window.png": (88, 88),
    "decor-window-dusk.png": (88, 88),
    "decor-window-night.png": (88, 88),
    "bench.png": (88, 16),
    "chair.png": (52, 78),
}

# The shipped SCENE.surfaces entry strings — [0] and [1] must survive the
# append byte-identical (Pitfall 3: surfaces[0] is hard-coded by the spine
# renderer and the candle home; order is load-bearing).
SURFACE_0 = "{ x0: 16, x1: 88, y: 56 }"
SURFACE_1 = "{ x0: 216, x1: 336, y: 116 }"
SURFACE_2 = "{ x0: 124, x1: 212, y: 152 }"


def png_dims(path):
    """Width, height straight from the IHDR chunk (bytes 16-24)."""
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise AssertionError(f"{path.name} is not a PNG")
    return struct.unpack(">II", data[16:24])


def setUpModule():
    """Regenerate every sprite ONCE before the suite runs — the dims below
    are then pinned against deterministic codegen output, never stale disk."""
    proc = subprocess.run(
        [sys.executable, str(GENERATOR)],
        cwd=str(REPO_ROOT), capture_output=True, text=True)
    if proc.returncode != 0:
        raise AssertionError(
            "tools/gen_room_sprites.py exited "
            f"{proc.returncode}:\n{proc.stderr}")


class TestPngDimensions(unittest.TestCase):
    """Coverage 1-2: regeneration emitted the split sprites at pinned dims."""

    def test_split_sprite_dimensions(self):
        for name, (w, h) in PINNED_DIMS.items():
            path = ROOM / name
            self.assertTrue(path.is_file(),
                            f"{name} missing — the generator must emit it")
            self.assertEqual(
                png_dims(path), (w, h),
                f"{name} must be {w}x{h} (SC-3: windows re-cut to 88x88, "
                f"bench born at 88x16)")


class TestRegistryAgreement(unittest.TestCase):
    """Coverage 3: index.html, app.js and server.py agree (Pitfall 7)."""

    @classmethod
    def setUpClass(cls):
        cls.html = (REPO_ROOT / "index.html").read_text(encoding="utf-8")
        cls.app = (REPO_ROOT / "app.js").read_text(encoding="utf-8")

    def _button(self, dom_id):
        """The full <button ...>...</button> block for a room object."""
        start = self.html.find(f'id="{dom_id}"')
        self.assertNotEqual(start, -1,
                            f'index.html has no id="{dom_id}" button')
        end = self.html.find("</button>", start)
        return self.html[start:end]

    def test_index_html_window_and_bench(self):
        window = self._button("room-obj-window")
        self.assertIn("--w:88;--h:88", window,
                      "index.html window button must carry --h:88 "
                      "(the seat left the sprite)")
        bench = self._button("room-obj-bench")
        self.assertIn("--x:124;--y:152;--w:88;--h:16", bench,
                      "index.html bench button must pin the default "
                      "geometry --x:124;--y:152;--w:88;--h:16")
        self.assertIn('data-cls="floorwall"', bench,
                      "26.5-09 F9 (the owner): the bench is DUAL-BAND "
                      "(floorwall) — seats on the floor near it, floats "
                      "free-Y on the wall (the floating bench)")
        self.assertIn("assets/room/bench.png", bench,
                      "the bench button must show assets/room/bench.png")

    def test_app_js_catalog_and_sprite_fence(self):
        self.assertRegex(
            self.app,
            re.compile(r"window:\s*\{\s*name:\s*'window',\s*sprite:\s*"
                       r"'decor-window',\s*cls:\s*'wall',\s*w:\s*88,\s*"
                       r"h:\s*88"),
            "app.js CATALOG window entry must read w: 88, h: 88")
        self.assertRegex(
            self.app,
            re.compile(r"'decor-window':\s*\{\s*w:\s*88,\s*h:\s*88\s*\}"),
            "app.js CAT_SPRITES 'decor-window' must read { w: 88, h: 88 }")
        self.assertRegex(
            self.app,
            re.compile(r"bench:\s*\{\s*name:\s*'bench',\s*sprite:\s*"
                       r"'bench',\s*cls:\s*'floorwall',\s*w:\s*88,\s*h:\s*16"),
            "app.js CATALOG must carry the bench entry "
            "{name:'bench', sprite:'bench', cls:'floorwall', w:88, h:16}")
        self.assertRegex(
            self.app,
            re.compile(r"'bench':\s*\{\s*w:\s*88,\s*h:\s*16\s*\}"),
            "app.js CAT_SPRITES must carry 'bench': { w: 88, h: 16 }")

    def test_app_js_room_object_ids(self):
        m = re.search(r"var ROOM_OBJECT_IDS = \[([^\]]*)\]", self.app)
        self.assertIsNotNone(m, "app.js must declare ROOM_OBJECT_IDS")
        self.assertIn("'bench'", m.group(1),
                      "ROOM_OBJECT_IDS must include 'bench' — otherwise "
                      "the bench never arms for design-mode drags")

    def test_server_layout_objects(self):
        self.assertEqual(
            server.LAYOUT_OBJECTS.get("window"), (88, 88, "wall"),
            'server.py LAYOUT_OBJECTS must carry "window": '
            '(88, 88, "wall")')
        self.assertEqual(
            server.LAYOUT_OBJECTS.get("bench"), (88, 16, "floorwall"),
            'server.py LAYOUT_OBJECTS must carry "bench": '
            '(88, 16, "floorwall") — 26.5-09 F9 floating bench')
        self.assertIn("floorwall", server.LAYOUT_CLASSES,
                      "floorwall must be a recognized layout class")
        self.assertNotIn(
            "bench", server.FUNCTIONAL_OBJECTS,
            "the bench is NOT a loop container — it must stay out of "
            "FUNCTIONAL_OBJECTS (removable decor, like the window)")

    def test_server_accepts_bench_drag(self):
        # Functional acceptance (T-26.5-18): an in-bounds, on-grid bench
        # position posts clean through validate_layout from LAYOUT_OBJECTS
        # membership alone.
        err = server.validate_layout(
            {"version": 1, "objects": {"bench": {"x": 120, "y": 152}}})
        self.assertIsNone(
            err,
            f"validate_layout must accept a legal bench drag, got: {err}")
        # 26.5-09 F9 (the owner): the FLOATING bench — a wall-band position
        # (well above the floor line) posts clean too.
        err = server.validate_layout(
            {"version": 1, "objects": {"bench": {"x": 120, "y": 60}}})
        self.assertIsNone(
            err,
            f"validate_layout must accept a floating (wall-band) bench, "
            f"got: {err}")
        # And the in-bounds fence still holds for the bench row.
        err = server.validate_layout(
            {"version": 1, "objects": {"bench": {"x": 120, "y": 204}}})
        self.assertIsNotNone(
            err, "a bench posted below the room floor must be refused")


class TestChairRegistryAgreement(unittest.TestCase):
    """26.5-09 UAT F16 (the owner): the office chair promoted from fixed
    scenery to a full arrangeable object — the bench's pattern end-to-end.
    Same Pitfall-7 gate: the chair's geometry must agree across all three
    registries or a legitimate design-mode drag is silently refused."""

    @classmethod
    def setUpClass(cls):
        cls.html = (REPO_ROOT / "index.html").read_text(encoding="utf-8")
        cls.app = (REPO_ROOT / "app.js").read_text(encoding="utf-8")

    def test_index_html_chair_button(self):
        start = self.html.find('id="room-obj-chair"')
        self.assertNotEqual(start, -1,
                            'index.html has no id="room-obj-chair" button — '
                            "the chair must be a real room object, not a "
                            "scenery span")
        chair = self.html[start:self.html.find("</button>", start)]
        self.assertIn("--x:250;--y:90;--w:52;--h:78", chair,
                      "index.html chair button must pin the default "
                      "geometry --x:250;--y:90;--w:52;--h:78")
        self.assertIn('data-cls="floor"', chair,
                      "the chair is floor class — it seats on the floor "
                      "line, never hosts anything")
        self.assertIn('room-passive', chair,
                      "the chair has NO everyday click action — it must "
                      "carry room-passive so outside design mode it never "
                      "intercepts a click meant for a functional object "
                      "(the F7 rule)")
        self.assertIn("assets/room/chair.png", chair,
                      "the chair button must show assets/room/chair.png")
        self.assertNotIn("room-scenery", self.html,
                         "no scenery span may remain — the chair was the "
                         "only one, and it is a room object now")

    def test_app_js_chair_registries(self):
        self.assertRegex(
            self.app,
            re.compile(r"chair:\s*\{\s*name:\s*'chair',\s*sprite:\s*"
                       r"'chair',\s*cls:\s*'floor',\s*w:\s*52,\s*h:\s*78"),
            "app.js CATALOG must carry the chair entry "
            "{name:'chair', sprite:'chair', cls:'floor', w:52, h:78}")
        self.assertRegex(
            self.app,
            re.compile(r"'chair':\s*\{\s*w:\s*52,\s*h:\s*78\s*\}"),
            "app.js CAT_SPRITES must carry 'chair': { w: 52, h: 78 }")
        m = re.search(r"var ROOM_OBJECT_IDS = \[([^\]]*)\]", self.app)
        self.assertIsNotNone(m, "app.js must declare ROOM_OBJECT_IDS")
        self.assertIn("'chair'", m.group(1),
                      "ROOM_OBJECT_IDS must include 'chair' — otherwise "
                      "the chair never arms for design-mode drags")
        m = re.search(r"var SURFACE_HOSTS = \[([^\]]*)\]", self.app)
        self.assertIsNotNone(m, "app.js must declare SURFACE_HOSTS")
        self.assertNotIn("'chair'", m.group(1),
                         "nothing seats ON the chair — it must stay out "
                         "of SURFACE_HOSTS (no surface hosting)")

    def test_server_chair_row(self):
        self.assertEqual(
            server.LAYOUT_OBJECTS.get("chair"), (52, 78, "floor"),
            'server.py LAYOUT_OBJECTS must carry "chair": '
            '(52, 78, "floor") — 26.5-09 F16')
        self.assertNotIn(
            "chair", server.FUNCTIONAL_OBJECTS,
            "the chair is NOT a loop container — it must stay out of "
            "FUNCTIONAL_OBJECTS (movable/removable decor, like the bench)")

    def test_server_accepts_chair_drag(self):
        # Functional acceptance (the bench's T-26.5-18 shape): an
        # in-bounds, on-grid chair position posts clean through
        # validate_layout from LAYOUT_OBJECTS membership alone.
        err = server.validate_layout(
            {"version": 1, "objects": {"chair": {"x": 252, "y": 90}}})
        self.assertIsNone(
            err,
            f"validate_layout must accept a legal chair drag, got: {err}")
        # And the in-bounds fence still holds for the chair row
        # (52x78 -> y may not exceed 216 - 78 = 138).
        err = server.validate_layout(
            {"version": 1, "objects": {"chair": {"x": 252, "y": 180}}})
        self.assertIsNotNone(
            err, "a chair posted below the room floor must be refused")


# ---------------------------------------------------------------------------
# 26.9-04: THE STICKER SHEET REGENERATION GATE
#
# READ THIS BEFORE SIMPLIFYING ANYTHING BELOW. Four steps, and steps 1 and 4
# exist ONLY to close degenerate passes — each looks removable to anyone who
# has not seen what it stops, and each stops a DIFFERENT degenerate
# implementation:
#
#   Step 1 (existence + shape). The gate's original form was step 3 alone:
#   "regenerate twice, the tree is clean the second time." AN EMPTY ROSTER
#   SATISFIES THAT ON THE FIRST RUN — generate nothing and the tree is clean.
#   A gate whose easiest pass is doing no work measures nothing. Step 1 is
#   what makes "the sheet exists, at a width DERIVED from the roster" a
#   measured statement.
#
#   Step 4 (ink per cell). A generator emitting a fully TRANSPARENT sheet of
#   the correct size PASSES STEPS 1 THROUGH 3: right dimensions, agreeing
#   tables, byte-stable, and completely blank. Step 4 is the cheapest
#   assertion a blank sheet fails.
#
# Neither is redundant with the other, and NEITHER IS A SUBSTITUTE FOR THE
# HUMAN LANDING CHECK in tools/SPRITES.md §7.5 — reading the exported PNG as
# an image before committing. Step 4 does not check that the art is GOOD; it
# checks that art exists. On this plan the human check is what caught two
# stickers that passed all four steps and still read as solid bricks.
#
# Step 3 has its own trap, recorded because it is this phase's named defect
# class landing INSIDE the instrument built to catch it: `git status
# --porcelain` EXITS 0 WHETHER THE TREE IS DIRTY OR CLEAN. A step 3 written
# on that exit code alone cannot go red — it states the requirement and
# measures nothing. The assertion below reads the OUTPUT and reports the
# offending paths.
# ---------------------------------------------------------------------------

STICKER_SHEET = ROOM / "notebook-stickers.png"
STICKER_CELL_H = 48                 # 24 scene px, upscaled x2 by write_png
# The three palette entries no new sprite in this phase may contain: --green
# is the ONE feature wall and plant foliage, --accent (coral) is the selection
# outline's attention signal, --never is the destructive red. Checked by
# DECODING the sheet, never by grepping the generator — a colour composed at
# runtime would not appear in the source at all.
FORBIDDEN_RGB = {
    (0x4f, 0x7b, 0x43): "--green",
    (0xe8, 0x50, 0x3a): "--accent (coral)",
    (0x9a, 0x28, 0x28): "--never (destructive red)",
}


def _png_rgba_rows(path):
    """Decode an 8-bit RGBA PNG to a list of per-row bytes. All five PNG
    filter types are implemented rather than assuming the generator's filter
    0 — a wrong decode would make step 4 silently unreliable, which is the
    exact failure mode step 4 exists to prevent."""
    data = path.read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise AssertionError(f"{path.name} is not a PNG")
    width, height = struct.unpack(">II", data[16:24])
    idat, i = b"", 8
    while i < len(data):
        length = struct.unpack(">I", data[i:i + 4])[0]
        if data[i + 4:i + 8] == b"IDAT":
            idat += data[i + 8:i + 8 + length]
        i += 12 + length
    raw = zlib.decompress(idat)
    stride, rows, prev, p = width * 4, [], bytearray(width * 4), 0
    for _ in range(height):
        ftype = raw[p]
        p += 1
        line = bytearray(raw[p:p + stride])
        p += stride
        for x in range(stride):
            a = line[x - 4] if x >= 4 else 0
            b = prev[x]
            c = prev[x - 4] if x >= 4 else 0
            if ftype == 1:
                line[x] = (line[x] + a) & 255
            elif ftype == 2:
                line[x] = (line[x] + b) & 255
            elif ftype == 3:
                line[x] = (line[x] + (a + b) // 2) & 255
            elif ftype == 4:
                q = a + b - c
                pa, pb, pc = abs(q - a), abs(q - b), abs(q - c)
                line[x] = (line[x] +
                           (a if pa <= pb and pa <= pc else
                            (b if pb <= pc else c))) & 255
        rows.append(bytes(line))
        prev = line
    return width, height, rows


def _generator_roster():
    """The SHEET'S OWN source of truth: the (name, width) tuple that lays the
    strip out. Parsed rather than hardcoded so a Tier-C cut is a roster edit
    plus a regen and this gate follows automatically — a hardcoded copy here
    would be a fourth spelling and the one that drifts silently."""
    src = (REPO_ROOT / "tools" / "gen_room_sprites.py").read_text(
        encoding="utf-8")
    block = re.search(r"^NB_STICKERS = \((.*?)\n\)", src, re.S | re.M)
    assert block, "gen_room_sprites.py must declare NB_STICKERS = ( ... )"
    return [(m.group(1), int(m.group(2))) for m in
            re.finditer(r"\('([a-z-]+)',\s*(\d+)\)", block.group(1))]


def _client_roster():
    """app.js NB_STICKERS — name -> {x, w}, the crop table."""
    src = (REPO_ROOT / "app.js").read_text(encoding="utf-8")
    block = re.search(r"var NB_STICKERS = \{(.*?)\n  \};", src, re.S)
    assert block, "app.js must declare var NB_STICKERS = { ... };"
    return {m.group(1): {"x": int(m.group(2)), "w": int(m.group(3))}
            for m in re.finditer(
                r"'([a-z-]+)':\s*\{\s*x:\s*(\d+),\s*w:\s*(\d+)\s*\}",
                block.group(1))}


class TestStickerSheetRegenGate(unittest.TestCase):
    """Coverage 5: the four-step gate. Read the block comment above."""

    @classmethod
    def setUpClass(cls):
        cls.gen = _generator_roster()
        cls.client = _client_roster()

    # ---- STEP 1: existence and shape ------------------------------------
    def test_step1_sheet_exists_at_the_roster_derived_shape(self):
        self.assertTrue(
            STICKER_SHEET.exists(),
            "assets/room/notebook-stickers.png must exist — an EMPTY ROSTER "
            "generates nothing and leaves the tree clean, which is exactly "
            "the degenerate pass this step closes")
        # THE FLOOR, AND IT IS LOAD-BEARING — do not fold it into the width
        # assertion below. Driving the empty-roster mutation (M-1a') with
        # only the width check active showed step 1 PASSING: `expected_w` is
        # DERIVED from the roster, so an empty roster sends both sides to
        # zero together and `0 == 0` holds. A derived expectation that
        # follows the mutation measures nothing. The floor is the six Tier B
        # core stickers, which UI-SPEC E4 states as a contract ("the marks
        # tab can never be empty — compiled art with a floor of 6 core
        # stickers"), so a Tier C cut from ten to six still passes and an
        # emptied roster cannot.
        self.assertGreaterEqual(
            len(self.gen), 6,
            "the roster floor is the six core stickers (UI-SPEC E4: the "
            "marks tab can never be empty); found "
            f"{len(self.gen)} — an empty roster is the 'do no work' "
            "degenerate pass this whole step exists to close")
        expected_w = sum(w for _, w in self.gen) * 2
        self.assertGreater(expected_w, 0, "a zero-width sheet is not a sheet")
        width, height = png_dims(STICKER_SHEET)
        self.assertEqual(
            width, expected_w,
            f"the sheet's IHDR width must equal sum(roster widths) * 2 = "
            f"{expected_w}; read {width}. A roster edit without a regen "
            f"lands here.")
        self.assertEqual(
            height, STICKER_CELL_H,
            f"the sheet is one strip of uniform 24 scene-px cells, so its "
            f"height is {STICKER_CELL_H}; read {height}")

    # ---- STEP 2: roster agreement ---------------------------------------
    def test_step2_all_three_rosters_agree_in_both_directions(self):
        gen_names = [n for n, _ in self.gen]
        self.assertEqual(
            sorted(gen_names), sorted(self.client),
            "the generator roster and app.js NB_STICKERS must hold the same "
            "names — a sticker added to one side only lands here")
        self.assertEqual(
            sorted(gen_names), sorted(server.DECOR_SPRITES),
            "the generator roster and server.py DECOR_SPRITES must hold the "
            "same names — a name the server refuses is a sticker that can be "
            "picked and never saved")

    def test_step2_client_offsets_are_the_running_prefix_sums(self):
        """Derived arithmetically from the widths, never eyeballed against
        the table — the table is the thing under test."""
        run = 0
        for name, width in self.gen:
            self.assertIn(name, self.client)
            self.assertEqual(
                self.client[name]["w"], width,
                f"{name}: app.js width {self.client[name]['w']} disagrees "
                f"with the sheet's {width}")
            self.assertEqual(
                self.client[name]["x"], run,
                f"{name}: app.js x is {self.client[name]['x']} but the "
                f"running prefix sum of the preceding widths is {run} — the "
                f"crop would land on a neighbouring sticker")
            run += width

    # ---- STEP 3: byte stability -----------------------------------------
    def test_step3a_two_consecutive_generations_are_identical(self):
        """The determinism half, measured WITHOUT git: a clock, a global, or
        an unseeded random.* in the generator lands here even in a shallow
        checkout with no history."""
        first = hashlib.sha256(STICKER_SHEET.read_bytes()).hexdigest()
        proc = subprocess.run([sys.executable, str(GENERATOR)],
                              cwd=str(REPO_ROOT), capture_output=True,
                              text=True)
        self.assertEqual(proc.returncode, 0, proc.stderr)
        second = hashlib.sha256(STICKER_SHEET.read_bytes()).hexdigest()
        self.assertEqual(
            first, second,
            "two consecutive generations produced different bytes — the "
            "generator is not deterministic (SPRITES §7.4: every random goes "
            "through random.Random(<fixed literal seed>))")

    def test_step3b_the_asset_directory_is_clean_after_regeneration(self):
        """The drift half: the committed PNGs ARE what the generator emits.
        A hand-edited or hand-committed sheet the generator does not
        reproduce lands here.

        THE ASSERTION READS THE OUTPUT, NOT THE EXIT CODE. `git status
        --porcelain` exits 0 on a dirty tree as readily as on a clean one, so
        a check written on its status could never go red."""
        proc = subprocess.run(
            ["git", "status", "--porcelain", "assets/room"],
            cwd=str(REPO_ROOT), capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0,
                         f"git status itself failed: {proc.stderr}")
        self.assertEqual(
            proc.stdout.strip(), "",
            "assets/room is not clean after regeneration — the generator "
            "does not reproduce the committed bytes. Offending paths:\n" +
            proc.stdout)

    # ---- STEP 4: ink per cell -------------------------------------------
    def test_step4_every_roster_cell_carries_ink(self):
        """THE LAST DEGENERATE PASS. A fully transparent sheet of the correct
        size satisfies steps 1-3 completely: right dimensions, agreeing
        tables, byte-stable, and blank."""
        width, height, rows = _png_rgba_rows(STICKER_SHEET)
        blank = []
        for name, cell in sorted(self.client.items(),
                                 key=lambda kv: kv[1]["x"]):
            x0, wpx = cell["x"] * 2, cell["w"] * 2
            opaque = sum(
                1 for y in range(height) for i in range(x0, x0 + wpx)
                if rows[y][i * 4 + 3] > 0)
            if opaque == 0:
                blank.append(name)
        self.assertEqual(
            blank, [],
            "these roster cells contain no pixel with alpha > 0 — the "
            "sticker is blank: " + ", ".join(blank))

    def test_the_sheet_contains_no_forbidden_palette_entry(self):
        """Decoded, not grepped: a colour composed at runtime never appears
        in the generator's source, so a source grep would miss it."""
        _, height, rows = _png_rgba_rows(STICKER_SHEET)
        seen = set()
        for y in range(height):
            row = rows[y]
            for i in range(len(row) // 4):
                if row[i * 4 + 3] > 0:
                    seen.add((row[i * 4], row[i * 4 + 1], row[i * 4 + 2]))
        hits = sorted(label for rgb, label in FORBIDDEN_RGB.items()
                      if rgb in seen)
        self.assertEqual(
            hits, [],
            "no new sprite in this phase may spend green, coral or "
            "destructive red; found: " + ", ".join(hits))

    def test_the_generator_imports_no_third_party_module(self):
        """T-26.9-SC: the generator is stdlib-only and Pillow is neither
        installed nor needed.

        THE GREP IS ANCHORED, AND THAT IS THE WHOLE POINT. The plan's stated
        criterion was 'grep -c for a Pillow import reads 0'; the NAIVE form
        `grep -ci 'PIL\\|Pillow'` over this generator reads 5, every hit
        PROSE ('spills', 'pile'). A criterion satisfied by prose is this
        phase's named defect class. Anchored to a line that actually starts
        an import statement, it reads 0."""
        src = (REPO_ROOT / "tools" / "gen_room_sprites.py").read_text(
            encoding="utf-8")
        hits = re.findall(r"^[ \t]*(?:import|from)[ \t]+(?:PIL|pillow)\b",
                          src, re.M | re.I)
        self.assertEqual(hits, [], f"third-party import found: {hits}")
        for name in ("requirements.txt", "requirements.in",
                     "pyproject.toml", "Pipfile"):
            self.assertFalse(
                (REPO_ROOT / name).exists(),
                f"{name} must not exist — the zero-dependency law")


class TestScenePins(unittest.TestCase):
    """Coverage 4: SCENE.surfaces — [0]/[1] byte-identical, [2] appended."""

    @classmethod
    def setUpClass(cls):
        app = (REPO_ROOT / "app.js").read_text(encoding="utf-8")
        start = app.find("var SCENE = {")
        assert start != -1, "app.js must declare var SCENE = {"
        end = app.find("};", start)
        cls.scene = app[start:end]

    def test_surfaces_entries_and_order(self):
        i0 = self.scene.find(SURFACE_0)
        i1 = self.scene.find(SURFACE_1)
        i2 = self.scene.find(SURFACE_2)
        self.assertNotEqual(i0, -1,
                            "surfaces[0] (bookshelf top) must stay the "
                            f"shipped byte-identical string {SURFACE_0}")
        self.assertNotEqual(i1, -1,
                            "surfaces[1] (desk top) must stay the shipped "
                            f"byte-identical string {SURFACE_1}")
        self.assertNotEqual(i2, -1,
                            "surfaces[2] (bench cushion top) must be "
                            f"appended as {SURFACE_2}")
        self.assertLess(i0, i1, "surfaces order is load-bearing: bookshelf "
                                "before desk (Pitfall 3)")
        self.assertLess(i1, i2, "the bench entry is APPEND-ONLY: it must "
                                "follow the desk entry, never precede it")


# ---------------------------------------------------------------------------
# 26.98-04: THE WIDENED + INVERTED PALETTE GATE (SC-7)
#
# WHAT CHANGED, AND WHY ONE HALF WOULD NOT HAVE DONE. The only decoded-pixel
# palette gate in this repo until today is test_the_sheet_contains_no_forbidden_
# palette_entry above: it looks at ONE sheet and asks whether it contains one of
# THREE forbidden hexes. 36 of the 37 shipped PNGs were never decoded by any
# assertion, and a sprite painted entirely in colours nobody chose passes that
# gate cleanly. SC-7 wants the whole directory AND the question inverted — not
# "does this contain a bad colour" but "is every colour in this one somebody
# chose". Widening the scope while keeping a three-hex deny-list would STILL
# pass a fully off-palette sprite, so both changes are load-bearing and neither
# is redundant with the other.
#
# An allow-list can only ever prove the ABSENCE of strays. It can never prove
# the outline is still there — so the presence half below is a separate
# assertion, not a corollary.
#
# THE FIVE ANTI-VACUITY ANSWERS:
#   1. It cannot pass before the work: 36 of these 37 files had never been
#      decoded by any assertion in this repo, and the first widened run
#      reported three strays in 13 files (recorded in 26.98-04-SUMMARY.md).
#   2. It cannot pass after a deliberate break: painting one pixel of the
#      destructive red into a sprite drove it red by hand on 2026-08-24 (the
#      verbatim message is in the SUMMARY), and
#      test_the_stray_detector_reports_a_synthetic_stray drives the predicate
#      red INSIDE the committed suite, forever, with no tree change at all —
#      so the gate carries its own proof rather than only the day it was
#      written.
#   3. A degenerate glob cannot slide through: ROOM_PNG_COUNT is asserted BY
#      VALUE before the loop begins, so a glob that matched nothing fails on
#      the count rather than passing a zero-iteration emptiness assertion.
#   4. It reads evaluation, not source: every colour is DECODED from committed
#      bytes. A colour composed at runtime never appears in the generator's
#      text, which is why the older gate above says "decoded, not grepped".
#   5. There is no grep in it at all, so it cannot be satisfied by a comment.
#
# HER PALETTE RULING, AND WHAT THIS LIST IS KEYED TO (SPRITES.md 9.2).
# 2026-08-24, the owner, ruling from the side-by-side built in 26.98-03: "Keep the
# current colours." The handoff's two 10-step ramps are DECLINED — recorded
# narrowly: it declines the whole-room repaint and nothing else, it is "not
# now" rather than "never", it was made on an acknowledged confound, and it
# does NOT touch her same-day permission to propose colours outside the palette
# for the desk rework and for new sprites. ALLOWED_RGB is therefore keyed to
# WHAT SHIPS TODAY. Had she adopted the ramps it would STILL be keyed to what
# ships today, because the repaint is rung D and rung D is below this phase's
# cut line — an allow-list keyed to the ramps would fail all 37 sprites on disk
# on the day it landed.
#
# THE ALLOW-LIST IS NEVER WIDENED TO MAKE THE GATE GREEN (T-26.98-22). It is
# split in two below precisely so that widening it is impossible to do quietly:
# CHARTER_RGB is the written palette, ADDED_RGB is every hex the shipped art
# carries that the written palette never recorded, and both lengths are pinned
# BY VALUE by test_the_allow_list_is_the_charter_plus_recorded_additions. A
# sixteenth entry cannot appear without editing a number that a human reviewer
# will see in the diff.
# ---------------------------------------------------------------------------

# The written palette: SPRITES.md 2's table (11 rows) MINUS the destructive red
# --never, which 2's own hard constraint says is "never used in any sprite" —
# so it is not merely unallowed here, its pixel count must be ZERO (asserted
# separately below). Plus 8.2's two approved additions of 2026-08-06 (twelve),
# plus 8.2's eight of 2026-08-25 (Ruling 1, the owner — the desk scene's eight,
# written into SPRITES.md 8.2 in the same commit that added them here):
# 12 + 8 = 20, plus 8.2's twenty-one of 2026-08-25 (the night-shade ruling,
# the owner — "Yes — ship the evening", the desk evening's twenty-one, written
# into SPRITES.md 8.2 in the same commit that added them here):
# 20 + 21 = 41. An ADDITION, not a re-measurement.
CHARTER_RGB = {
    (0xee, 0xea, 0xe1): "--paper",          # 2, warm off-white walls
    (0xdc, 0xd5, 0xc8): "--paper-shadow",   # 2, shadows and hairlines
    (0xfb, 0xf7, 0xee): "--card",           # 2, daylight highlights, paper
    (0xe0, 0xc7, 0x9a): "--btn-bg",         # 2, blonde bamboo wood
    (0xcd, 0xa8, 0x6e): "--wood-deep",      # 2, deeper wood
    (0x2c, 0x28, 0x23): "--ink",            # 2, THE outline ink (ruled 08-07)
    (0x55, 0x50, 0x47): "--ink-soft",       # 2, mid-shadow tones
    (0xb7, 0xb2, 0xa8): "--stone",          # 2, pale stone
    (0x4f, 0x7b, 0x43): "--green",          # 2, the ONE living green
    (0xe8, 0x50, 0x3a): "--accent",         # 2, coral, <=4 art px (see below)
    (0xa8, 0x80, 0x4f): "wood-dark",        # 8.2, approved 2026-08-06
    (0x3c, 0x62, 0x34): "green-dark",       # 8.2, approved 2026-08-06
    # The desk scene's eight — SPRITES.md 8.2, Ruling 1, the owner, 2026-08-25.
    # Sprite art only, never chrome, never tokens.css.
    (0x6f, 0x9c, 0x5a): "leaf-lit",         # 8.2, approved 2026-08-25
    (0x94, 0xa4, 0x87): "dusty-sage",       # 8.2, approved 2026-08-25
    (0x5f, 0x7d, 0x8c): "ceramic-blue",     # 8.2, approved 2026-08-25 — THE
                                            # FIRST COOL COLOUR in the room
    (0x8a, 0xa3, 0xae): "ceramic-lit",      # 8.2, approved 2026-08-25
    (0x4c, 0x66, 0x75): "ceramic-dark",     # 8.2, approved 2026-08-25
    (0xb0, 0x8a, 0x3e): "brass",            # 8.2, approved 2026-08-25
    (0xc9, 0xa7, 0x5c): "brass-lit",        # 8.2, approved 2026-08-25
    (0xcf, 0xe0, 0xe2): "glass-water",      # 8.2, approved 2026-08-25
    # 26.999, the owner, 2026-08-25 — the dusty rose (sticky note + card-box
    # tabs, "The Desk Surfaces" canvas). Flagged to her as a NEW colour;
    # her answer, verbatim: "I don't really care about adding new colors
    # from the new items, i think the design system is for the UI" — which
    # is also the palette-SCOPE ruling recorded in SPRITES.md 8.2 (new item
    # sprites may carry new colours; the token discipline binds UI chrome).
    # Sprite art only, never chrome, never tokens.css.
    (0xd4, 0x9e, 0x9e): "dusty-rose",       # 8.2, approved 2026-08-25
    # The desk evening's twenty-one — SPRITES.md 8.2, the night-shade ruling,
    # the owner, 2026-08-25. The shipped day plate through the approved night
    # pass (gen_desk_station_night: one flat ink dim at 0.46, two warm zones
    # lifted with the checkerboard edge at radii 34/66, wall light clipped at
    # the desk line, the stepped lit strip under the flame at x=300, snapped,
    # no ramp-quantise). She was shown the day plate beside the night plate
    # at real size (26.9995-07-night-shades.png, planning tracker's phase
    # folder) and told all 21 sat outside the then-approved 23; her verbatim
    # selection: "Yes — ship the evening". Listed in the R-7 record
    # (tools/ROOM-HANDOFF.md) by pixel count, and entered here in that order.
    # desk-station-night.png ONLY; sprite art, never chrome, never tokens.css.
    (0x90, 0x90, 0x90): "night-01",         # 8.2, approved 2026-08-25 — the
                                            # dimmed --paper wall
    (0x84, 0x6c, 0x48): "night-02",         # 8.2, approved 2026-08-25
    (0x90, 0x78, 0x60): "night-03",         # 8.2, approved 2026-08-25
    (0x9c, 0x9c, 0x90): "night-04",         # 8.2, approved 2026-08-25
    (0x6c, 0x54, 0x3c): "night-05",         # 8.2, approved 2026-08-25
    (0x48, 0x3c, 0x30): "night-06",         # 8.2, approved 2026-08-25
    (0x90, 0x84, 0x78): "night-07",         # 8.2, approved 2026-08-25
    (0x30, 0x24, 0x24): "night-ink",        # 8.2, approved 2026-08-25 — the
                                            # night register's OWN ink: #2c2823
                                            # through the 0.46 dim + the
                                            # 12-step snap (44 is not a
                                            # multiple of 12, so literal ink
                                            # cannot survive the pass)
    (0xa8, 0xa8, 0x9c): "night-09",         # 8.2, approved 2026-08-25
    (0x9c, 0x90, 0x84): "night-10",         # 8.2, approved 2026-08-25
    (0xa8, 0xa8, 0x90): "night-11",         # 8.2, approved 2026-08-25
    (0x78, 0x78, 0x6c): "night-12",         # 8.2, approved 2026-08-25
    (0xa8, 0x9c, 0x84): "night-13",         # 8.2, approved 2026-08-25
    (0x9c, 0x90, 0x90): "night-14",         # 8.2, approved 2026-08-25
    (0xb4, 0xa8, 0x9c): "night-15",         # 8.2, approved 2026-08-25
    (0xcc, 0xc0, 0xb4): "night-16",         # 8.2, approved 2026-08-25
    (0xb4, 0xb4, 0xa8): "night-17",         # 8.2, approved 2026-08-25
    (0xc0, 0xa8, 0x9c): "night-18",         # 8.2, approved 2026-08-25
    (0xc0, 0xc0, 0xb4): "night-19",         # 8.2, approved 2026-08-25
    (0x9c, 0x90, 0x78): "night-20",         # 8.2, approved 2026-08-25
    (0xa8, 0x9c, 0x90): "night-21",         # 8.2, approved 2026-08-25
}

# THREE HEXES THE SHIPPED ART CARRIES THAT SPRITES.md 2 NEVER WROTE DOWN.
# 26.98-03 measured and pinned this drift while discovering the shipped palette
# for its control arm; the first run of the widened gate below reported exactly
# the same three and nothing else. Each is a NAMED, DATED token in
# tools/gen_room_sprites.py's PAL with its own recorded provenance, so these are
# colours somebody chose that the table was never updated to hold — not strays.
# They are recorded here rather than silently folded into CHARTER_RGB, because
# the distinction between "the written palette" and "what the art actually
# spends" is the whole finding. Recorded 2026-08-24 (26.98-04); the reconciling
# edit to SPRITES.md 2 is a documentation change this plan does not own.
ADDED_RGB = {
    (0xb5, 0x62, 0x3a): "--clay",       # PAL['clay'], the scene-only
                                        # terracotta pop named in the
                                        # generator's own docstring (Phase 24)
    (0xcf, 0x83, 0x54): "--clay-light", # PAL['claylt'], the lit terracotta and
                                        # the candle flame's warm tip
    (0x2b, 0x2f, 0x3e): "--night-sky",  # PAL['nightsky'], generator line 21:
                                        # "25-01 (D-04b): the ONE new hex — the
                                        # night window's sky, --ink leaned
                                        # toward blue. Sprite art only, never
                                        # chrome."
}

ALLOWED_RGB = dict(CHARTER_RGB)
ALLOWED_RGB.update(ADDED_RGB)

# Pinned BY VALUE: 37 (pinned 2026-08-24, re-measured that wave —
# 26.98-RESEARCH.md said 34) + 10 (the ten desk sprites of Plan 04, landed
# 2026-08-25, authorised by Ruling 1 of 2026-08-25: plant-snake, plant-pothos,
# plant-succulent, plant-cactus, plant-cutting, plant-budvase, lamp-desk, mug,
# pen-cup, watering-can) = 47, + 1 (desk-station-night.png, the desk's
# evening plate, landed 2026-08-25, authorised by R-7 and the night-shade
# ruling of 2026-08-25 — "Yes — ship the evening", the owner) = 48.
# AN ADDITION, NOT A RE-MEASUREMENT — a count pin re-measured from the
# directory it counts is not a pin. Seen red first: with the night plate on
# disk and this pin still 47 the gate reported "48 != 47" verbatim.
# Asserted BEFORE the loop runs — a glob that matched nothing dies here rather
# than passing an emptiness assertion over zero iterations.
# 48 -> 50 on 2026-08-25 (26.999): + cardbox.png (the librarian's memory of
# you — her design sitting + approved canvas) and desk-sticky.png (the desk
# note's sticky pair). An addition of exactly two, seen red first (the
# directory-clean gates named both files verbatim before this moved.)
# 50 -> 51 the same evening (26.999): + paper-stack.png — the guided first
# pass's visual door, her ruling from the built room (the wall sentence
# removed; a small stack of papers pressed, not read).
# 51 -> 54 the same night (26.999): + album-open.png, notebook-marked.png,
# paper-stack-waiting.png — the three QUIET WAIT MARKS, her gentler-mark
# ruling over the red-dot ask (no red, no numbers; an art swap while
# something new truly waits). An addition of exactly three, seen red first.
ROOM_PNG_COUNT = 54

INK_RGB = (0x2c, 0x28, 0x23)              # 2 / 9.1 — the outline, ruled twice
REJECTED_OUTLINE_RGB = (0x4a, 0x3a, 0x2c)  # 8.1 rejected 08-06, 9.1 again 08-07
DESTRUCTIVE_RED_RGB = (0x9a, 0x28, 0x28)   # 2 --never: never used in any sprite
GREEN_RGB = (0x4f, 0x7b, 0x43)
CORAL_RGB = (0xe8, 0x50, 0x3a)

# write_png doubles the art grid before writing, so ONE ART PIXEL IS A 2x2 BLOCK
# OF FOUR PNG PIXELS. Every ceiling below is stated in art pixels and converted,
# because a ceiling read off raw PNG counts is wrong by exactly 4x.
PNG_PX_PER_ART_PX = 4

# The outline-is-PRESENT list. Measured 2026-08-24 over the shipped set: 36 of
# the 37 carry --ink. Pinned BY NAME (not derived from the glob — a derived list
# would follow a sprite that lost its outline straight down and report green).
# 2026-08-25 (Plan 04): + the 10 desk sprites — every one is an object sprite
# in SPRITES.md 7.2's ink-silhouette register and ends in silhouette() ink, so
# ALL TEN join this half of the partition and DECKLE_EXEMPT_SPRITES stays at
# its single paper entry. 36 + 10 = 46 — an addition, not a re-measurement.
# 2026-08-25 (Plan 07): + desk-station-night.png, the desk's evening plate
# (R-7; the night-shade ruling, "Yes — ship the evening"). 46 + 1 = 47 — an
# addition, not a re-measurement. Seen red first: with the name in the tuple
# and the pin still 46 the gate reported "47 != 46" verbatim. ⚠ ITS OUTLINE
# IS IN THE NIGHT REGISTER: the pass sends every mix through a 12-step snap
# and 44 is not a multiple of 12, so the day ink #2c2823 CANNOT appear in the
# night plate — its ink rides through the 0.46 dim as #302424 ("night-ink",
# among the 21 she approved). NIGHT_REGISTER_OUTLINES below carries that
# per-sprite tone, so presence is still asserted, in the plate's own ink.
OUTLINED_SPRITES = (
    "album-open.png",
    "album-page.png", "album.png", "bench.png", "bg.png", "bookshelf.png",
    "cardbox.png",
    "chair.png", "cursor-inkpen.png", "cursor-pencil.png", "decor-art-b.png",
    "decor-art.png", "decor-books.png", "decor-candle-anim.png",
    "decor-candle.png", "decor-plant-b.png", "decor-plant.png",
    "decor-rug-b.png", "decor-rug.png", "decor-window-dusk.png",
    "decor-window-night.png", "decor-window.png", "desk-sticky.png",
    "desk-station-night.png",
    "desk-station.png",
    "desk.png", "journal.png", "lamp-desk.png", "mug.png",
    "notebook-decor.png", "notebook-marked.png", "notebook-station.png",
    "notebook-stickers.png", "notebook.png", "paper-stack-waiting.png",
    "paper-stack.png",
    "pen-cup.png",
    "plant-budvase.png", "plant-cactus.png", "plant-cutting.png",
    "plant-pothos.png", "plant-snake.png", "plant-succulent.png",
    "reflection-book-0.png",
    "reflection-book-1.png", "reflection-book-2.png", "reflection-book-3.png",
    "reflection-book-4.png", "reflection-book-5.png", "shelf-station.png",
    "spread-frame-album.png", "spread-frame-book.png", "watering-can.png",
)
# 47 -> 49 on 2026-08-25 (26.999): + cardbox.png and desk-sticky.png, both
# in the 7.2 ink-silhouette object register (silhouette() ink, like the
# ten). An addition of exactly two, not a re-measurement.
# 49 -> 50 the same evening (26.999): + paper-stack.png, same register.
# 50 -> 53 the same night (26.999): + the three quiet wait marks — each a
# same-canvas variant of an already-outlined base (album-open of album,
# notebook-marked of notebook, paper-stack-waiting of paper-stack), so all
# three inherit the register. An addition of exactly three, seen red first.
OUTLINED_SPRITE_COUNT = 53

# The night register's outline tones, per sprite (2026-08-25, Plan 07). A
# sprite named here is asserted to carry ITS OWN ink — the day ink through
# the approved night pass — because the pass's 12-step snap makes literal
# #2c2823 impossible in its output. Every sprite NOT named here is asserted
# to carry #2c2823 exactly as before; this map widens nothing for them.
NIGHT_REGISTER_OUTLINES = {
    "desk-station-night.png": (0x30, 0x24, 0x24),   # "night-ink" — #2c2823
                                                    # through dim 0.46 + snap
}

# The one exemption, and it is documented rather than convenient: SPRITES.md
# 7.5's landing checklist reads "Object sprites: stepped corners + ink rim (OR
# DECKLE, FOR PAPER)". spread-frame-paper.png is the loose sheet on a felt
# blotter — gen_spread_frame_paper() draws a jittered deckle edge in --stone and
# deliberately no ink rim. The two tuples must PARTITION the directory, so a
# thirty-eighth PNG cannot escape both lists silently.
DECKLE_EXEMPT_SPRITES = ("spread-frame-paper.png",)

# 2's hard constraint, as REWRITTEN by her ruling of 2026-08-25: "--green
# appears as the feature wall (in bg.png), as plant foliage — and, ruled
# 2026-08-25, as the pencil in pen-cup.png. Nowhere else." Her words, verbatim
# (the selection label she chose from the two-crossings render): "Green
# pencil". The ruling names one pencil in one sprite — no other non-foliage
# use is opened.
#
# MEASURED 2026-08-24, AND THE SHIPPED ART IS WIDER THAN THE ORIGINAL
# SENTENCE. Ten files carried --green then: the feature wall (bg.png, and
# shelf-station.png which paints the same wall behind the shelf), the two
# plants, foliage seen through all three windows, a framed piece of foliage
# art, one green book spine on the decor shelf and one green reflection-book
# spine. This list PINS WHAT IS TRUE, names the drift instead of hiding it,
# and stops an unlisted file spending the one living green. Reconciling 2's
# original sentence with that pre-existing drift is a separate, owner-facing
# question this plan does not answer.
#
# 2026-08-25 (Plan 04): 10 (pinned 2026-08-24) + 6 foliage carriers of the
# new desk plants (plant-snake, plant-pothos, plant-succulent, plant-cactus,
# plant-cutting, plant-budvase — foliage, squarely inside the old sentence)
# + 1 ruled non-foliage carrier (pen-cup.png — "Green pencil", the owner,
# 2026-08-25) = 17. AN ADDITION, NOT A RE-MEASUREMENT.
GREEN_SPRITES = (
    "bg.png", "decor-art.png", "decor-books.png", "decor-plant-b.png",
    "decor-plant.png", "decor-window-dusk.png", "decor-window-night.png",
    "decor-window.png", "pen-cup.png", "plant-budvase.png",
    "plant-cactus.png", "plant-cutting.png", "plant-pothos.png",
    "plant-snake.png", "plant-succulent.png", "reflection-book-1.png",
    "shelf-station.png",
)
GREEN_SPRITE_COUNT = 17

# 2's hard constraint, as REWRITTEN by her ruling of 2026-08-25: "Coral
# appears in scene art as the candle flame (decor-candle.png /
# decor-candle-anim.png, <=4 art px per sprite and per frame) — and, ruled
# 2026-08-25, as the red flowers on plant-cactus.png and plant-budvase.png,
# drawn as the designer drew them. Never an interaction signal — that half of
# the old rule stands untouched." Her words, verbatim (the selection label she
# chose from the two-crossings render): "Red flowers".
#
# MEASURED 2026-08-24 (the candle): coral appeared in exactly two files, both
# the candle flame — decor-candle.png (1 art px) and the three-frame strip
# decor-candle-anim.png (3, 1, 1 art px per frame). A NAIVE WHOLE-SCENE TOTAL
# WOULD READ 6 ART PIXELS AND FAIL A CEILING OF 4 ON ART THAT IS NOT WRONG,
# because an animation strip is the SAME one-sprite detail drawn once per frame.
# So the candle's ceiling is applied where 2 states it — per sprite, and per
# FRAME for a strip. Both halves are still needed: the ceiling alone would
# permit coral to spread to a new sprite, and the roster alone would permit
# the candle to become a coral object.
#
# THE ROSTER, 2026-08-25 (Plan 04): 2 (pinned 2026-08-24) + 2 (the ruled
# flowers, "Red flowers", the owner, 2026-08-25) = 4. AN ADDITION, NOT A
# RE-MEASUREMENT.
#
# THE CEILING, 2026-08-25 (Plan 04): now PER SPRITE. The candle KEEPS its
# 4-art-px-per-frame ceiling exactly as pinned 2026-08-24 — the ruling names
# two flowers, not the flame, and a single raised ceiling would have quietly
# let the candle grow fivefold. The two flowers are pinned at what the
# faithful port actually emits: 12 art px on the cactus and 21 on the bud
# vase, measured from the committed bytes (Plan 03's render note said 13 for
# the cactus — that counted the flower disc before its claylt tip overwrites
# one pixel; the EMITTED sprite carries 12). These are pinned at the ruled
# art's own numbers so the NEXT change to either flower fails here and gets
# argued — a ceiling re-measured from the art it limits would not be a pin.
CORAL_SPRITES = ("decor-candle.png", "decor-candle-anim.png",
                 "plant-budvase.png", "plant-cactus.png")
CORAL_SPRITE_COUNT = 4         # 2 + 2 (Ruling on the flowers, 2026-08-25)
CORAL_ART_PX_CEILING = 4       # the candle's per-frame ceiling — unmoved by
                               # the ruling, which names the flowers only
CORAL_ART_PX_PER_SPRITE = {    # the ruled flowers, pinned at measured value
    "plant-cactus.png": 12,    # measured from committed bytes, 2026-08-25
    "plant-budvase.png": 21,   # measured from committed bytes, 2026-08-25
}
CANDLE_FRAME_ART_W = 10        # SPRITES.md 4: decor-candle-anim is N frames of
                               # 10x22 scene px side by side


def _room_pngs():
    """Every PNG in assets/room/, sorted for determinism."""
    return sorted(ROOM.glob("*.png"))


def _rgb_counts_from_rows(width, height, rows):
    """Opaque RGB triple -> PNG pixel count. A fully transparent pixel carries
    no colour, so alpha 0 is skipped: an RGBA (0,0,0,0) pixel is not black."""
    counts = {}
    for y in range(height):
        row = rows[y]
        for i in range(width):
            if row[i * 4 + 3] > 0:
                key = (row[i * 4], row[i * 4 + 1], row[i * 4 + 2])
                counts[key] = counts.get(key, 0) + 1
    return counts


def _strays_in_rows(width, height, rows, allowed=None):
    """THE INVERTED PREDICATE, isolated so it can be driven red IN MEMORY with
    no tree change at all: seen - allowed, not forbidden & seen. Returns the
    offending triples mapped to their pixel counts, because a failure message
    that names the colour but not how much of it there is cannot be triaged."""
    allowed = ALLOWED_RGB if allowed is None else allowed
    return {rgb: n
            for rgb, n in _rgb_counts_from_rows(width, height, rows).items()
            if rgb not in allowed}


_ROOM_DECODE_CACHE = {}


def _room_rgb_counts(path):
    """Decode once per file per process — the whole directory is ~0.9s."""
    key = str(path)
    if key not in _ROOM_DECODE_CACHE:
        width, height, rows = _png_rgba_rows(path)
        _ROOM_DECODE_CACHE[key] = _rgb_counts_from_rows(width, height, rows)
    return _ROOM_DECODE_CACHE[key]


class TestRoomPalette(unittest.TestCase):
    """26.98-04 / SC-7: every shipped sprite is asked whether ALL of its
    colours are ones somebody chose, and the outline is proven PRESENT rather
    than merely permitted. Read the block comment above before changing
    anything here."""

    def test_the_allow_list_is_the_charter_plus_recorded_additions(self):
        """The anti-drift device. Widening the allow-list to make a sprite pass
        is this project's most repeated defect; these three by-value pins make
        it impossible to do without editing a number in the diff."""
        self.assertEqual(
            len(CHARTER_RGB), 42,   # 12 (pinned 2026-08-24) + 8 (Ruling 1,
                                    # 2026-08-25) = 20, + 21 (the night-shade
                                    # ruling, 2026-08-25 — "Yes — ship the
                                    # evening") = 41, + 1 (the dusty rose,
                                    # 26.999, the owner, 2026-08-25 — flagged as
                                    # a new colour on the canvas and taken)
                                    # = 42 — an addition, not a
                                    # re-measurement. Seen red first: "41 !=
                                    # 42" with the rose in and this pin
                                    # unmoved.
            "CHARTER_RGB must hold exactly the written palette: SPRITES.md "
            "2's eleven rows MINUS --never (#9a2828, which must appear zero "
            "times, not merely be unallowed), plus 8.2's two approved "
            "additions #a8804f and #3c6234, plus 8.2's eight of 2026-08-25 "
            "(Ruling 1, the owner — the desk scene's eight), plus 8.2's "
            "twenty-one of 2026-08-25 (the night-shade ruling, the owner — the "
            "desk evening's twenty-one), plus 8.2's dusty rose of 2026-08-25 "
            "(26.999, the owner — the desk-surface pair). Found "
            f"{len(CHARTER_RGB)}.")
        self.assertNotIn(
            DESTRUCTIVE_RED_RGB, CHARTER_RGB,
            "--never (#9a2828) must NOT be allow-listed — 2's hard "
            "constraint is that it is never used in any sprite, which is a "
            "zero-count assertion, not a permission")
        self.assertNotIn(
            REJECTED_OUTLINE_RGB, ALLOWED_RGB,
            "#4a3a2c was rejected on 2026-08-06 (8.1) and again on "
            "2026-08-07 (9.1). It is not an approved sprite colour and must "
            "never be allow-listed.")
        self.assertEqual(
            len(ADDED_RGB), 3,
            "ADDED_RGB records the hexes the shipped art carries that "
            "SPRITES.md 2 never wrote down. It was measured at THREE on "
            "2026-08-24 (#b5623a --clay, #cf8354 --clay-light, #2b2f3e "
            f"--night-sky). Found {len(ADDED_RGB)}. A fourth entry means "
            "somebody widened the allow-list — that is a DECISION with a "
            "token, a reason and a date, never a fix.")
        # 15 (pinned 2026-08-24) + 8 (Ruling 1, 2026-08-25) = 23, + 21 (the
        # night-shade ruling, 2026-08-25) = 44, + 1 (the dusty rose, 26.999,
        # the owner, 2026-08-25) = 45 — an addition, not a re-measurement.
        # ADDED_RGB stays 3. Seen red first: "45 != 44" with the rose in.
        self.assertEqual(len(ALLOWED_RGB), 45)

    def test_the_stray_detector_reports_a_synthetic_stray(self):
        """ANTI-VACUITY ANSWER 2, living in the committed suite forever. Two
        pixels, built in memory, no file touched: one allowed, one stray. A
        predicate that reported nothing — the degenerate implementation this
        whole gate is worth nothing without — fails right here."""
        stray = (0x12, 0x34, 0x56)
        self.assertNotIn(stray, ALLOWED_RGB)
        allowed_px = (0xee, 0xea, 0xe1)          # --paper
        self.assertIn(allowed_px, ALLOWED_RGB)
        rows = [bytes(allowed_px) + b"\xff" + bytes(stray) + b"\xff"]
        found = _strays_in_rows(2, 1, rows)
        self.assertEqual(
            found, {stray: 1},
            "the stray detector did not report a colour that is not in the "
            f"allow-list; it returned {found}. A predicate that cannot see a "
            "planted stray cannot see a real one.")
        # And the transparent-pixel rule: alpha 0 is not a colour.
        rows = [bytes(stray) + b"\x00"]
        self.assertEqual(
            _strays_in_rows(1, 1, rows), {},
            "a fully transparent pixel must not be read as a colour — "
            "RGBA (0,0,0,0) is not black")

    def test_every_room_png_carries_only_allowed_palette_entries(self):
        """SC-7, both halves: the whole directory, and the question inverted."""
        files = _room_pngs()
        # BY VALUE, BEFORE THE LOOP. A glob that matched nothing dies here.
        self.assertEqual(
            len(files), ROOM_PNG_COUNT,
            f"assets/room holds {len(files)} PNG(s); ROOM_PNG_COUNT is pinned "
            f"at {ROOM_PNG_COUNT}. If a sprite was legitimately added or cut, "
            "update this number DELIBERATELY — it is the pin that stops a "
            "glob which matched nothing from passing every assertion below "
            "over zero iterations.")
        offenders = []
        for path in files:
            counts = _room_rgb_counts(path)
            strays = {rgb: n for rgb, n in counts.items()
                      if rgb not in ALLOWED_RGB}
            for rgb, n in sorted(strays.items()):
                offenders.append(
                    "  %s: #%02x%02x%02x x %d px" % (path.name, rgb[0],
                                                     rgb[1], rgb[2], n))
        self.assertEqual(
            offenders, [],
            "these sprites carry colours nobody chose (seen - ALLOWED_RGB is "
            "not empty). Fix the GENERATOR so the colour is never painted, or "
            "decide the colour is legitimate and add it to ADDED_RGB with a "
            "token name, a reason and a date — never widen the list to make "
            "this green:\n" + "\n".join(offenders))

    def test_the_outline_ink_is_present_in_every_outlined_sprite(self):
        """PRESENCE, which an allow-list can NEVER prove. She ruled on
        2026-08-06 and again on 2026-08-07 that #2c2823 stays; a sprite that
        lost its outline carries only allowed colours and passes the gate
        above cleanly."""
        self.assertEqual(
            len(OUTLINED_SPRITES), OUTLINED_SPRITE_COUNT,
            f"OUTLINED_SPRITES holds {len(OUTLINED_SPRITES)} name(s); the "
            f"count is pinned at {OUTLINED_SPRITE_COUNT}")
        # The two lists must PARTITION the directory — otherwise a new sprite
        # simply appears in neither and is never asked the question.
        # (2026-08-25, Plan 04: the overlap check used to compare
        # sorted(A)+sorted(B) against the sorted union, which silently relied
        # on every A name sorting before every B name — true only until
        # watering-can.png arrived and sorted after spread-frame-paper.png.
        # It now tests overlap and duplicates directly.)
        overlap = set(OUTLINED_SPRITES) & set(DECKLE_EXEMPT_SPRITES)
        self.assertEqual(
            overlap, set(),
            "OUTLINED_SPRITES and DECKLE_EXEMPT_SPRITES must not overlap: "
            + ", ".join(sorted(overlap)))
        self.assertEqual(
            len(OUTLINED_SPRITES) + len(DECKLE_EXEMPT_SPRITES),
            len(set(OUTLINED_SPRITES) | set(DECKLE_EXEMPT_SPRITES)),
            "a name appears more than once within the two partition tuples")
        self.assertEqual(
            sorted(p.name for p in _room_pngs()),
            sorted(set(OUTLINED_SPRITES) | set(DECKLE_EXEMPT_SPRITES)),
            "every PNG in assets/room must be either an outlined sprite or a "
            "named, reasoned deckle exemption (SPRITES.md 7.5: 'stepped "
            "corners + ink rim (or deckle, for paper)'). A sprite in neither "
            "list is never asked whether it kept its outline.")
        missing = [name for name in OUTLINED_SPRITES
                   if NIGHT_REGISTER_OUTLINES.get(name, INK_RGB)
                   not in _room_rgb_counts(ROOM / name)]
        self.assertEqual(
            missing, [],
            "these sprites carry NO outline-ink pixel — the outline is gone "
            "(#2c2823 for day sprites; the NIGHT_REGISTER_OUTLINES tone for a "
            "night plate, whose 12-step snap makes literal #2c2823 "
            "impossible). The owner ruled 2026-08-06 (8.1) and again 2026-08-07 "
            "(9.1) that #2c2823 stays, and the handoff's 'remove all "
            "outlines' clause is struck: " + ", ".join(missing))

    def test_the_destructive_red_and_the_rejected_outline_hex_appear_nowhere(self):
        """Two zero-count assertions. Neither is implied by the allow-list:
        'not allowed' would let a single pixel be argued about, and a count of
        zero cannot."""
        for rgb, why in (
            (DESTRUCTIVE_RED_RGB,
             "SPRITES.md 2: --never (#9a2828) is 'not used in sprites — "
             "destructive chrome only'"),
            (REJECTED_OUTLINE_RGB,
             "#4a3a2c was REJECTED on 2026-08-06 (8.1) and again on "
             "2026-08-07 (9.1); a blind colour-replace over the shipped set "
             "was explicitly refused"),
        ):
            total, where = 0, []
            for path in _room_pngs():
                n = _room_rgb_counts(path).get(rgb, 0)
                if n:
                    total += n
                    where.append("%s x %d px" % (path.name, n))
            self.assertEqual(
                total, 0,
                "#%02x%02x%02x must decode in ZERO files. %s. Found: %s"
                % (rgb[0], rgb[1], rgb[2], why, ", ".join(where)))

    def test_the_one_living_green_appears_only_where_it_belongs(self):
        """2's hard constraint, which nothing checked until today. See the
        GREEN_SPRITES comment: this pins what the art actually does and names
        the drift from 2's sentence rather than papering over it."""
        self.assertEqual(
            len(GREEN_SPRITES), GREEN_SPRITE_COUNT,
            f"GREEN_SPRITES holds {len(GREEN_SPRITES)}; pinned at "
            f"{GREEN_SPRITE_COUNT}")
        carriers = sorted(p.name for p in _room_pngs()
                          if GREEN_RGB in _room_rgb_counts(p))
        self.assertEqual(
            carriers, sorted(GREEN_SPRITES),
            "the ONE living green (#4f7b43) is spent in a different set of "
            "sprites than the pinned one. 2 (as rewritten by her ruling of "
            "2026-08-25): '--green appears as the feature wall, as plant "
            "foliage — and, ruled 2026-08-25, as the pencil in pen-cup.png. "
            "Nowhere else.'\n"
            f"  pinned: {sorted(GREEN_SPRITES)}\n"
            f"  found:  {carriers}")

    def test_coral_stays_within_its_pinned_ceilings(self):
        """2's other hard constraint, in its post-ruling shape (2026-08-25,
        "Red flowers"). Read the CORAL_SPRITES comment before touching any
        ceiling. The candle keeps its 4-art-px-per-frame ceiling; the two
        ruled flowers are pinned at their measured emitted counts. Frame
        slicing applies ONLY to the anim strip — the plants are single
        sprites, and slicing them at the candle's frame width would split one
        flower across two fictional frames."""
        self.assertEqual(len(CORAL_SPRITES), CORAL_SPRITE_COUNT)
        carriers = sorted(p.name for p in _room_pngs()
                          if CORAL_RGB in _room_rgb_counts(p))
        self.assertEqual(
            carriers, sorted(CORAL_SPRITES),
            "coral (#e8503a) appears in scene art as the candle flame — and, "
            "ruled 2026-08-25 ('Red flowers', SPRITES.md 2), as the flowers "
            "on plant-cactus.png and plant-budvase.png. Never an interaction "
            "signal, and never any sprite off this roster. It is spent in a "
            f"different set of sprites than the pinned one.\n  pinned: "
            f"{sorted(CORAL_SPRITES)}\n  found:  {carriers}")
        for name in CORAL_SPRITES:
            width, height, rows = _png_rgba_rows(ROOM / name)
            if name.endswith("-anim.png"):
                frame_px = CANDLE_FRAME_ART_W * 2
                spans = [(f * frame_px, min(width, (f + 1) * frame_px))
                         for f in range(max(1, width // frame_px))]
            else:
                spans = [(0, width)]
            ceiling = CORAL_ART_PX_PER_SPRITE.get(name, CORAL_ART_PX_CEILING)
            for f, (lo, hi) in enumerate(spans):
                n = sum(1 for y in range(height) for i in range(lo, hi)
                        if rows[y][i * 4 + 3] > 0
                        and (rows[y][i * 4], rows[y][i * 4 + 1],
                             rows[y][i * 4 + 2]) == CORAL_RGB)
                art_px = n // PNG_PX_PER_ART_PX
                if name in CORAL_ART_PX_PER_SPRITE:
                    self.assertEqual(
                        art_px, ceiling,
                        f"{name} frame {f} spends {art_px} art px of coral; "
                        f"the ruled flower is PINNED at {ceiling} (measured "
                        "2026-08-25) — grown OR shrunk, it gets argued.")
                else:
                    self.assertLessEqual(
                        art_px, ceiling,
                        f"{name} frame {f} spends {art_px} art px of coral; "
                        f"the pinned ceiling for this sprite is {ceiling} "
                        "art px (SPRITES.md 2 — the candle's 4 per frame). "
                        "Coral is never a whole object and never an "
                        "interaction signal.")


# ---------------------------------------------------------------------------
# 26.98-04: THE FINALIZED_BY_HAND SKIP-GUARD, PROVEN AGAINST A CONTROL
#
# WHY A CONTROL ARM IS NOT OPTIONAL. The guarded arm alone — "the guarded file
# did not change" — is passed trivially by a generator that crashed on its first
# line, by a generator that never started, and by a guard set that swallows
# every filename. Each of those is a degenerate implementation that LOOKS like
# success and destroys the mechanism. The control arm is a second file, NOT in
# the guard set, put through the identical invocation, whose hash MUST CHANGE.
# One arm is not a proof.
#
# WHY BOTH ARMS MUST RESTORE. setUpModule regenerates all of assets/room/ before
# this suite asserts anything, and every later class here reads those bytes. A
# guard test that leaves sentinel bytes behind poisons every suite that runs
# after it (T-26.98-21). The restore therefore runs in a finally, AND again in
# tearDownClass, so a failed assertion cannot leave the tree broken — and it is
# verified by reading `git status --porcelain assets/room`'s OUTPUT, never its
# exit code, which is zero on a dirty tree as readily as on a clean one.
#
# THE FIVE ANTI-VACUITY ANSWERS:
#   1. It cannot pass before the work: FINALIZED_BY_HAND did not exist, and
#      write_png wrote every file unconditionally, so the guarded arm's hash
#      changed.
#   2. It cannot pass after a deliberate break: emptying the guard set mid-test
#      (or moving the guard out of write_png to the dispatch loop, which leaves
#      the ~30 call sites unguarded) makes the guarded arm fail.
#   3. A degenerate implementation fails the CONTROL arm — a guard that skips
#      everything, a generator that never ran, a subprocess that died on import.
#   4. It reads evaluation, not source: both arms SHA-256 real bytes on disk
#      after a real subprocess really ran. No grep of the generator could tell
#      whether the guard is reached.
#   5. There is no grep in it, so it cannot be satisfied by a comment. (The
#      seat itself is checked by inspect.getsource of write_png, which reads the
#      function's own source object, not a file scan.)
#
# WHY THE SUBPROCESS EXECS A PATCHED SOURCE RATHER THAN IMPORTING THE MODULE.
# tools/gen_room_sprites.py runs its whole dispatch loop at MODULE level (there
# is no `if __name__ == "__main__"` guard), so importing it generates before any
# monkeypatch could land. The driver below therefore compiles the REAL generator
# source with the REAL __file__ — so ROOM resolves to the real assets/room/ and
# every line of write_png is the shipped line — and patches exactly ONE token:
# the CONTENTS of the frozenset, which is precisely the datum a future commit
# will edit when the first hand-finished sprite lands. The guard's logic is not
# patched.
# ---------------------------------------------------------------------------

GUARDED_SPRITE = "bench.png"      # small, deterministic, no other test writes it
CONTROL_SPRITE = "chair.png"      # NOT in the guard set — its hash MUST change
GUARD_SENTINEL = (b"SENTINEL-26.98-04 these bytes are not a PNG and must be "
                  b"overwritten by the generator unless the guard skipped\n")

_GUARD_DRIVER = r"""
import sys
gen, guarded = sys.argv[1], sys.argv[2]
src = open(gen, encoding='utf-8').read()
needle = 'FINALIZED_BY_HAND = frozenset()'
assert src.count(needle) == 1, (
    'gen_room_sprites.py must declare FINALIZED_BY_HAND = frozenset() exactly '
    'once at module level; the two-arm guard test patches its CONTENTS only')
patched = src.replace(
    needle, 'FINALIZED_BY_HAND = frozenset({%r})' % guarded, 1)
assert patched != src
exec(compile(patched, gen, 'exec'),
     {'__file__': gen, '__name__': '__main__'})
"""


_SEAT_PROBE = r"""
import sys, inspect, json
sys.path.insert(0, sys.argv[1])
import gen_room_sprites as g
src = inspect.getsource(g.write_png)
print('@@' + json.dumps({
    'is_frozenset': isinstance(g.FINALIZED_BY_HAND, frozenset),
    'contents': sorted(g.FINALIZED_BY_HAND),
    'guard_in_write_png': 'FINALIZED_BY_HAND' in src,
    'exists_check_in_write_png': 'os.path.exists' in src,
}))
"""


def _run_generator(extra_args=None):
    """The shipped generator, unpatched, empty guard set."""
    return subprocess.run([sys.executable, str(GENERATOR)] + (extra_args or []),
                          cwd=str(REPO_ROOT), capture_output=True, text=True)


class TestFinalizedByHandGuard(unittest.TestCase):
    """26.98-04: SPRITES.md 7.3's hand-off contract, in code at last. Read the
    block comment above — especially the paragraph on why one arm is not a
    proof — before simplifying anything here."""

    @classmethod
    def setUpClass(cls):
        cls.guarded_path = ROOM / GUARDED_SPRITE
        cls.control_path = ROOM / CONTROL_SPRITE
        cls.sentinel_hash = hashlib.sha256(GUARD_SENTINEL).hexdigest()
        try:
            # Both files get the IDENTICAL sentinel, so the only difference
            # between the arms is membership of the guard set.
            cls.guarded_path.write_bytes(GUARD_SENTINEL)
            cls.control_path.write_bytes(GUARD_SENTINEL)
            cls.proc = subprocess.run(
                [sys.executable, "-c", _GUARD_DRIVER,
                 str(GENERATOR), GUARDED_SPRITE],
                cwd=str(REPO_ROOT), capture_output=True, text=True)
            cls.guarded_hash = hashlib.sha256(
                cls.guarded_path.read_bytes()).hexdigest()
            cls.control_hash = hashlib.sha256(
                cls.control_path.read_bytes()).hexdigest()
            cls.control_bytes_head = cls.control_path.read_bytes()[:8]
        finally:
            cls.restore = cls._restore_the_tree()

    @classmethod
    def tearDownClass(cls):
        # Belt and braces: runs even when an assertion above failed, so a red
        # test never leaves sentinel bytes for the classes that follow.
        cls._restore_the_tree()

    @classmethod
    def _restore_the_tree(cls):
        """Regenerate with an EMPTY guard set (the shipped generator, no patch)
        and read `git status --porcelain assets/room`'s OUTPUT."""
        _ROOM_DECODE_CACHE.clear()
        gen = _run_generator()
        status = subprocess.run(
            ["git", "status", "--porcelain", "assets/room"],
            cwd=str(REPO_ROOT), capture_output=True, text=True)
        return {"gen_rc": gen.returncode, "gen_err": gen.stderr,
                "status_out": status.stdout, "status_err": status.stderr}

    def test_the_guard_is_seated_inside_the_single_write_choke_point(self):
        """T-26.98-19. A guard on the dispatch loop would leave all 30 call
        sites unguarded and a thirty-first would bypass it silently, so the
        seat is asserted on write_png's OWN source object via
        inspect.getsource — not by scanning the file, which cannot tell which
        function a line landed in.

        THE PROBE RUNS IN A SUBPROCESS ON PURPOSE. gen_room_sprites.py has no
        `if __name__ == "__main__"` guard, so importing it regenerates all of
        assets/room/ as an import side effect. In-process that would rewrite
        the shared tree at an arbitrary point in the suite; in a subprocess it
        is just one more deterministic regeneration, identical to the one
        setUpModule already ran."""
        proc = subprocess.run(
            [sys.executable, "-c", _SEAT_PROBE, str(REPO_ROOT / "tools")],
            cwd=str(REPO_ROOT), capture_output=True, text=True)
        self.assertEqual(proc.returncode, 0,
                         f"the seat probe failed:\n{proc.stderr}")
        verdict = None
        for line in proc.stdout.splitlines():
            if line.startswith("@@"):
                verdict = json.loads(line[2:])
        self.assertIsNotNone(
            verdict, f"the seat probe printed no verdict:\n{proc.stdout}")
        self.assertTrue(
            verdict["is_frozenset"],
            "FINALIZED_BY_HAND must be a frozenset — a mutable set invites a "
            "call site to edit the contract at run time")
        self.assertTrue(
            verdict["guard_in_write_png"],
            "the guard is not inside write_png. write_png is the ONLY place "
            "bytes reach disk and it is shared by all 30 call sites; a guard "
            "anywhere else leaves every one of them unguarded (T-26.98-19).")
        self.assertTrue(
            verdict["exists_check_in_write_png"],
            "the guard must require the destination to ALREADY EXIST before "
            "skipping, so a typo in FINALIZED_BY_HAND cannot silently delete a "
            "sprite from the roster (T-26.98-20)")

    def test_a_guarded_sprite_is_not_regenerated(self):
        """ARM ONE. Sentinel bytes over a GUARDED file survive the run."""
        self.assertEqual(
            self.guarded_hash, self.sentinel_hash,
            f"{GUARDED_SPRITE} was regenerated despite being in "
            "FINALIZED_BY_HAND — a hand-finished sprite would have been "
            "destroyed. SPRITES.md 7.3 is the contract this breaks.\n"
            f"  generator rc: {self.proc.returncode}\n"
            f"  stdout: {self.proc.stdout[-1500:]}\n"
            f"  stderr: {self.proc.stderr[-1500:]}")
        self.assertIn(
            GUARDED_SPRITE, self.proc.stdout,
            "each skip must print one line naming the preserved file — a "
            "regeneration that quietly did nothing is mysterious rather than "
            f"visible. stdout was:\n{self.proc.stdout[-1500:]}")

    def test_an_unguarded_sprite_is_still_regenerated(self):
        """ARM TWO — THE CONTROL, AND IT IS NOT OPTIONAL. Without it, a guard
        set that swallowed everything, or a generator that never started, would
        pass arm one and read as success."""
        self.assertNotEqual(
            self.control_hash, self.sentinel_hash,
            f"{CONTROL_SPRITE} still holds the sentinel bytes after the "
            "generator ran. It is NOT in the guard set, so it must have been "
            "rewritten. Either the guard is skipping files it was never given, "
            "or the generator never ran at all — and in both cases arm one's "
            "pass means nothing.\n"
            f"  generator rc: {self.proc.returncode}\n"
            f"  stdout: {self.proc.stdout[-1500:]}\n"
            f"  stderr: {self.proc.stderr[-1500:]}")
        self.assertEqual(
            self.control_bytes_head, b"\x89PNG\r\n\x1a\n",
            f"{CONTROL_SPRITE} changed but is not a PNG — the control arm "
            "measures that the generator WROTE, not merely that something "
            "touched the file")
        self.assertNotIn(
            CONTROL_SPRITE, self.proc.stdout,
            f"{CONTROL_SPRITE} is not in the guard set, so no skip line may "
            "name it")

    def test_the_restore_left_the_asset_directory_clean(self):
        """T-26.98-21. READS THE OUTPUT, NOT THE EXIT CODE — `git status
        --porcelain` exits 0 on a dirty tree as readily as on a clean one, so a
        check written on its status could never go red."""
        self.assertEqual(
            self.restore["gen_rc"], 0,
            "the restoring regeneration failed:\n" + self.restore["gen_err"])
        self.assertEqual(
            self.restore["status_out"].strip(), "",
            "the two-arm guard test left assets/room dirty — every suite that "
            "runs after this one is now reading poisoned bytes. Offending "
            "paths:\n" + self.restore["status_out"])


class TestRegenerationIsByteStable(unittest.TestCase):
    """SC-9's determinism half, MEASURED WITHOUT GIT — so it holds in a shallow
    checkout with no history, and cannot be satisfied by an exit code that is
    zero either way. The whole roster, not one sheet: a clock, a global or an
    unseeded random.* in any of the 30 call sites lands here."""

    def test_two_consecutive_generations_produce_identical_bytes(self):
        before = {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                  for p in _room_pngs()}
        self.assertEqual(
            len(before), ROOM_PNG_COUNT,
            f"hashed {len(before)} PNG(s); ROOM_PNG_COUNT is {ROOM_PNG_COUNT} "
            "— a glob that matched nothing must not pass this by comparing two "
            "empty dictionaries")
        proc = _run_generator()
        self.assertEqual(proc.returncode, 0, proc.stderr)
        _ROOM_DECODE_CACHE.clear()
        after = {p.name: hashlib.sha256(p.read_bytes()).hexdigest()
                 for p in _room_pngs()}
        drifted = sorted(n for n in before
                         if n not in after or before[n] != after[n])
        self.assertEqual(
            drifted, [],
            "these sprites came out different on a second generation — the "
            "generator is not deterministic (SPRITES.md 7.4: every random goes "
            "through random.Random(<fixed literal seed>), one unique seed per "
            "call site): " + ", ".join(drifted))


if __name__ == "__main__":
    unittest.main(verbosity=1)
